### ISSUE TITLE
Use logging library

### ISSUE THREAD

**Issue by jyn514** [charlesdaniels/bitshuffle#62]
We've got sufficient logging that handrolling our output is probably more effort than it's worth. Python has a builtin [`logging`](https://docs.python.org/3/library/logging.html) library that will be suitable; it supports `debug` through `critical` levels with a special `exception` level for backtraces.

This will allow interoperability with other libraries and reduce the size of the codebase considerably.

**Comment by jyn514** [comment]
Do we want a [datestamp for all logs](https://docs.python.org/3/howto/logging.html#displaying-the-date-time-in-messages)? It will make it more verbose but possibly help with automated runs.

**Comment by jyn514** [comment]
Hmm, there doesn't seem to be a builtin way to logically seperate parts of the message like we were doing before.

Currently:
```python
def warn(integer, *argv, **kwargs):
    error = "%s %d: %s" % (LEVELS[kwargs['severity']], integer, ERRORS[integer])
    for arg in argv:
        error += ": " + arg
```

To do this in the logger, we would have to call our own method every time, we couldn't use the builtin `logger.warning` method.

```python
>>> import logging
>>> logging.basicConfig(format='%(levelname)s %d: %(message)s')
>>> logging.warn('hi')                                         
--- Logging error ---
Traceback (most recent call last):
...
  File "/usr/local/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
TypeError: not enough arguments for format string
Call stack:
  File "<stdin>", line 1, in <module>
Message: 'hi'
Arguments: ()
>>> logging.warn('hi', 3)
--- Logging error ---
Traceback (most recent call last):
...
  File "/usr/local/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<stdin>", line 1, in <module>
Message: 'hi'
Arguments: (3,)
```

**Comment by jyn514** [comment]
Going to rewrite `warn` so that it works with `logger`. It does mean we'll have to log like this:
`logger.warn(logging_format("some message", 0))`, but it's better than messing around with instances of `logging.Logger` and `logging.Formatter`.

**Comment by charlesdaniels** [comment]
I seem to recall there was a way to setup a formatter and make it the default. I don’t remember quite how to do this, but I think it would do what we want. 

I would not do date stamps, since Bitshuffle should never be long running.

**Comment by jyn514** [comment]
right, I was looking at `logging.basicConfig` but it doesn't accept arbitrary arguments, the strings are predefined in `__init__.py`

**Comment by jyn514** [comment]
[got basics working](https://github.com/charlesdaniels/bitshuffle/commit/e2115c6f3ccbdd50ce5a96b212b3e581b11c9cf3), want to make debug levels consistent in both files before merging
